name: learn-actions
on:
 push:
  branches: main
 workflow_dispatch:
  inputs:
   buildType:
    default: DEV
jobs:
 build:
  runs-on: windows-latest
  steps:
  - name: Test
    run: |
     $sloc="//ent/dfs/dotnet/${{inputs.buildType}}"
     echo $sloc
