name: learn-actions
on:
 push:
  branches: main
 workflow_dispatch:
  inputs:
   buildType:
    default: DEV
jobs:
 build:
  runs-on: windows-latest
  steps:
  - name: Test
    run: |
     echo //ent/dfs/dotnet/${{github.event.inputs.buildType}}
